#!/usr/bin/env python3
"""Write vms/sources.mms for zstd: the library's and the CLI's objects, one
explicit MMS rule per object.  The lists are the ones zstd's own makefiles
use (lib/libzstd.mk, programs/Makefile): every .c in lib/common, compress,
decompress and dictBuilder, the legacy decoders v0.5-v0.7
(ZSTD_LEGACY_SUPPORT=5, the default), and every .c in programs/.

Usage: gen_sources.py <tree> > sources.mms
"""
import glob, os, sys

tree = sys.argv[1]
def vms_dir(rel):
    return '[.' + '.'.join(p.upper() for p in rel.split('/')) + ']'

lib = []
for d in ('common', 'compress', 'decompress', 'dictBuilder'):
    lib += sorted(glob.glob(os.path.join(tree, 'lib', d, '*.c')))
lib += sorted(f for f in glob.glob(os.path.join(tree, 'lib', 'legacy', 'zstd_v0*.c'))
              if os.path.basename(f)[7] in '567')
cli = sorted(glob.glob(os.path.join(tree, 'programs', '*.c')))

out = ['! Generated by tools/gen_sources.py - do not edit', '']
rules = []
for macro, objdir, flags, files in (('LIB_OBJS', '$(LOBJ)', 'LIB_CFLAGS', lib),
                                    ('CLI_OBJS', '$(OBJ)', 'CFLAGS', cli)):
    stems = [os.path.splitext(os.path.basename(f))[0] for f in files]
    dups = {s for s in stems if stems.count(s) > 1}
    if dups:
        sys.exit('duplicate object names: %s' % ' '.join(sorted(dups)))
    objs = ['%s%s.OBJ' % (objdir, s) for s in stems]
    out.append('%s = %s' % (macro, ', -\n\t'.join(objs)))
    out.append('')
    for f, o in zip(files, objs):
        rel = os.path.relpath(os.path.dirname(f), tree)
        rules += ['%s : %s%s' % (o, vms_dir(rel), os.path.basename(f)),
                  '\t- $(CC) $(%s) /OBJECT=$(MMS$TARGET) $(MMS$SOURCE)' % flags, '']
print('\n'.join(out + rules))
